# Generated by Django 5.2.1 on 2025-05-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(upload_to='uploads/')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('main_project', models.CharField(max_length=50)),
                ('add_resume', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
