# Generated by Django 5.2.1 on 2025-05-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_link', models.CharField(max_length=50)),
                ('logo_name', models.CharField(max_length=50)),
            ],
        ),
    ]
