# Generated by Django 5.2.1 on 2025-05-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_testimonials_alter_project_project_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
    ]
