# Generated by Django 5.2.1 on 2025-05-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='month',
        ),
    ]
