# Generated by Django 5.2.1 on 2025-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_remove_journey_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='year',
            field=models.IntegerField(),
        ),
    ]
