# Generated by Django 5.2.1 on 2025-05-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_alter_journey_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
